# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Ridge-penalized precision matrix estimation (c++)
#' @description Ridge-penalized Gaussian likelihood precision matrix estimation. Augmented from Adam Rothman's STAT 8931 code.
#'
#' @param S sample covariance matrix (denominator n)
#' @param lam tuning parameter for penalty
#' @return matrix of omega hat
#' @export
#' @examples
#' n = nrow(X)
#' sigma_ridgec(S = (n-1)/n*cov(X), lam = 0.1)
#'
sigma_ridgec <- function(S, lam) {
    .Call('_ADMMsigma_sigma_ridgec', PACKAGE = 'ADMMsigma', S, lam)
}

#' @title ADMM penalized precision matrix estimation (c++)
#' @description penalized Gaussian likelihood precision matrix estimation using the ADMM algorithm. Likelihood: Tr(S %*% Omega) - log(det(Omega)) + lambda((1 - alpha)/2 |Omega|_F^2 + alpha |Omega|_1)
#'
#' @param X data matrix
#' @param S option to specify sample covariance matrix (denominator n)
#' @param lam tuning parameter for penalty
#' @param alpha elasticnet mixing parameter [0, 1]: 0 = ridge, 1 = lasso/bridge
#' @param rho initial step size for ADMM
#' @param mu factor for primal and residual norms
#' @param tau1 adjustment for rho
#' @param tau2 adjustment for rho
#' @param crit criterion for convergence c("ADMM", "grad", "lik"). Option crit != "ADMM" will use tol1 as tolerance. Defaults to "ADMM"
#' @param tol1 absolute tolerance. Defaults to 1e-4
#' @param tol2 relative tolerance. Defaults to 1e-4
#' @param maxit maximum number of iterations
#' @return iterations, lam, omega
#' @export
#' @examples
#' ADMM_sigmac(X, lam = 0.1)
#'
ADMMsigmac <- function(S, lam, alpha = 1, rho = 2, mu = 10, tau1 = 2, tau2 = 2, crit = "ADMM", tol1 = 1e-4, tol2 = 1e-4, maxit = 1e3L) {
    .Call('_ADMMsigma_ADMMsigmac', PACKAGE = 'ADMMsigma', S, lam, alpha, rho, mu, tau1, tau2, crit, tol1, tol2, maxit)
}

#' @title Soft threshold (elementwise) (c++)
#' @description Elementwise soft thresholding function. Augmented from Adam Rothman's STAT 8931 code.
#'
#' @param s scalar
#' @param tau scalar
#' @return scalar
#' @export
#' @examples
#' softc(10, 5)
#'
softc <- function(s, tau) {
    .Call('_ADMMsigma_softc', PACKAGE = 'ADMMsigma', s, tau)
}

#' @title Soft threshold (matrix) (c++)
#' @description Matrix soft thresholding function. Requires `softc`. Augmented from Adam Rothman's STAT 8931 code.
#'
#' @param s matrix
#' @param tau scalar
#' @return soft threshold s matrix
#' @export
#' @examples
#' softmatrixc(10, 5)
#'
softmatrixc <- function(S, tau) {
    .Call('_ADMMsigma_softmatrixc', PACKAGE = 'ADMMsigma', S, tau)
}

